# Generated by Django 5.0.6 on 2024-06-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_et_prenom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('date_naissance', models.DateField()),
                ('numero_telephone', models.CharField(max_length=15)),
                ('is_staff', models.BooleanField(default=False)),
            ],
        ),
    ]
