# Generated by Django 5.0.6 on 2024-07-01 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_utilisateur_groups_utilisateur_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='user_permissions',
        ),
    ]
