# Generated by Django 5.0.6 on 2024-07-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_reservation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmée'), ('pending', 'En attente'), ('declined', 'Refusée')], default='pending', max_length=10),
        ),
    ]
